---

- hosts: web_server
  become: True
  gather_facts: False
  vars:
    packages: ['httpd','nano']
    version: 1
  roles:
    - install_packages
    - httpd
  post_tasks:
    - name: Copy v1 index.html to web server.
      tags: update_site
      copy:
        src: website/v1/index.html
        dest: /var/www/html/index.html
      when: version == 1

    - name: Copy v1 picture to web server.
      tags: update_site
      copy: 
        src: website/v1/puppy.gif
        dest: /var/www/html/puppy.gif
      when: version == 1

    - name: Copy v2 index.html to web server.
      tags: update_site
      copy: 
        src: website/v2/index.html
        dest: /var/www/html/index.html
      when: version == 2

    - name: Copy picture to web server.
      tags: update_site
      copy: 
        src: website/v2/soeasy.jpg
        dest: /var/www/html/soeasy.jpg
      when: version == 2
      